QMAKE_DEPENDS_FREETYPE_CC =
QMAKE_DEPENDS_FREETYPE_LD =
QMAKE_INCDIR_FREETYPE = $$[QT_INSTALL_HEADERS]/qtfreetype
QMAKE_DEFINES_FREETYPE = 
QMAKE_LIBS_FREETYPE =
QMAKE_LIBS_FREETYPE_DEBUG = $$[QT_INSTALL_LIBS]/libqtfreetype_debug.a
QMAKE_LIBS_FREETYPE_RELEASE = $$[QT_INSTALL_LIBS]/libqtfreetype.a
