QMAKE_DEPENDS_LIBPNG_CC =
QMAKE_DEPENDS_LIBPNG_LD =
QMAKE_INCDIR_LIBPNG = $$[QT_INSTALL_HEADERS]/qtlibpng
QMAKE_DEFINES_LIBPNG = 
QMAKE_LIBS_LIBPNG =
QMAKE_LIBS_LIBPNG_DEBUG = $$[QT_INSTALL_LIBS]/libqtlibpng_debug.a
QMAKE_LIBS_LIBPNG_RELEASE = $$[QT_INSTALL_LIBS]/libqtlibpng.a
