QMAKE_DEPENDS_LIBJPEG_CC =
QMAKE_DEPENDS_LIBJPEG_LD =
QMAKE_INCDIR_LIBJPEG = $$[QT_INSTALL_HEADERS]/qtlibjpeg
QMAKE_DEFINES_LIBJPEG = 
QMAKE_LIBS_LIBJPEG =
QMAKE_LIBS_LIBJPEG_DEBUG = $$[QT_INSTALL_LIBS]/libqtlibjpeg_debug.a
QMAKE_LIBS_LIBJPEG_RELEASE = $$[QT_INSTALL_LIBS]/libqtlibjpeg.a
