/* This file was generated by syncqt. */
#ifndef QT_QTQUICK3D_VERSION_H
#define QT_QTQUICK3D_VERSION_H

#define QTQUICK3D_VERSION_STR "5.15.13"

#define QTQUICK3D_VERSION 0x050F0D

#endif // QT_QTQUICK3D_VERSION_H
